/*
 * Copyright (c) 2026 Versori Group Inc
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the LICENSE file at the root of this repository.
 *
 * Change Date: 2030-03-01
 * Change License: Apache License, Version 2.0
 *
 * As of the Change Date, in accordance with the Business Source License,
 * use of this software will be governed by the Apache License, Version 2.0.
 */

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/spf13/cobra/doc"
	"github.com/versori/cli/pkg/cmd"
	"gopkg.in/yaml.v3"
)

// Patterns that Mintlify's MDX parser would otherwise mis-read as JSX and refuse
// to render.
//
//   - mdxPlaceholderRe: bare <placeholder> tokens (e.g. <key>, <project-id>).
//     The tight character class keeps real autolinks (<https://example.com>)
//     and shell redirection snippets (`echo <file`) untouched. Wrapped in
//     backticks so the rendered docs still hint "this is a parameter".
//   - { and }: MDX treats braces in prose as JS expressions. Backslash-escape
//     every occurrence so they render as literal punctuation. Handles nested
//     JSON examples (e.g. '{"a": {"b": 1}}') that a paired-brace regex can't.
var (
	mdxPlaceholderRe = regexp.MustCompile(`<([A-Za-z][A-Za-z0-9._-]*)>`)
	mdxFenceLineRe   = regexp.MustCompile("^\\s*```")
)

// mdxSafe neutralises markdown content that would otherwise trip Mintlify's MDX
// (acorn) parser. Applied to free-form prose fields (Description, flag Usage)
// before they hit the template. Content inside ``` fences is left untouched
// because MDX treats fenced code as literal.
func mdxSafe(s string) string {
	lines := strings.Split(s, "\n")
	inFence := false
	for i, line := range lines {
		if mdxFenceLineRe.MatchString(line) {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}
		line = mdxPlaceholderRe.ReplaceAllString(line, "`<$1>`")
		line = strings.ReplaceAll(line, "{", `\{`)
		line = strings.ReplaceAll(line, "}", `\}`)
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

// YamlDocOption represents a single CLI flag or option entry.
type YamlDocOption struct {
	Name         string `yaml:"name"`
	Shorthand    string `yaml:"shorthand,omitempty"`
	DefaultValue string `yaml:"default_value,omitempty"`
	Usage        string `yaml:"usage,omitempty"`
}

// YamlDoc maps the structure produced by doc.GenYamlTree for a single command.
type YamlDoc struct {
	Name string `yaml:"name"`

	// NameSegments is the path segments of the command name.
	// this is generated by splitting the Name field on spaces.
	NameSegments []string `yaml:"name_segments,omitempty"`

	// Command is the name of the command.
	// This is the last segment of the NameSegments.
	Command string `yaml:"command,omitempty"`

	// Parent is the name of the parent command.
	// This is the second to last segment of the NameSegments.
	Parent string `yaml:"parent,omitempty"`

	// SubCommands is a list of subcommands for this command.
	// based on the Parent Filed of the commands
	SubCommands []YamlDoc `yaml:"sub_commands,omitempty"`

	Synopsis         string          `yaml:"synopsis,omitempty"`
	Description      string          `yaml:"description,omitempty"`
	Usage            string          `yaml:"usage,omitempty"`
	Options          []YamlDocOption `yaml:"options,omitempty"`
	InheritedOptions []YamlDocOption `yaml:"inherited_options,omitempty"`
	SeeAlso          []string        `yaml:"see_also,omitempty"`
}

const markdownTemplate = `---
title: "{{ .Name | trimPrefix }}"
description: "{{ .Synopsis | singleLine | mdxSafe }}"
---

{{ .Description | mdxSafe }}

## Subcommands

| Subcommand | Description |
|---|---|
{{- range .SubCommands }}
| ` + "`{{ .Command }}`" + ` | {{ .Synopsis | singleLine | mdxSafe }} |
{{- end }}

---

{{- range .SubCommands }}

### ` + "`{{ .Name }}`" + `

{{ if hasSubCommands . }}

See the [{{ .Command }} reference]({{ prefix }}{{ relPath $ . }}{{ refExt }}) for detailed subcommands to {{ .Synopsis | lower | mdxSafe }}.
{{ else }}
{{ .Description | mdxSafe }}

` + "```sh" + `
{{ .Usage }}
` + "```" + `

{{ if .Options }}
**Flags:**
{{- range .Options }}
* {{ if .Shorthand }}` + "`{{ formatFlag .Shorthand }}`" + `, {{ end }}` + "`{{ formatFlagLong .Name }}`" + `: {{ .Usage | mdxSafe }}
{{- end }}
{{ end }}
{{ end }}

---
{{- end }}
`

var mdTmpl *template.Template
var docsPrefix string
var outDir string
var disableMDExt bool

func init() {
	flag.StringVar(&docsPrefix, "prefix", "/docs/", "Prefix for generated docs reference links")
	flag.StringVar(&outDir, "out", "./docs", "Output directory for generated markdown docs")
	flag.BoolVar(&disableMDExt, "disable-md-ext", false, "Disable the .md extension in generated reference links")

	var err error

	mdTmpl, err = template.New("markdown").Funcs(template.FuncMap{
		"prefix": func() string {
			return docsPrefix
		},
		"refExt": func() string {
			if disableMDExt {
				return ""
			}
			return ".md"
		},
		"hasSubCommands": func(d YamlDoc) bool {
			return len(d.SubCommands) > 0
		},
		"relPath": func(source, target YamlDoc) string {
			sourcePath := strings.TrimPrefix(source.Name, "versori ")
			sourcePath = strings.ReplaceAll(sourcePath, " ", "/")
			sourceDir := filepath.Dir(sourcePath)
			if sourceDir == "." {
				sourceDir = ""
			}

			targetPath := strings.TrimPrefix(target.Name, "versori ")
			targetPath = strings.ReplaceAll(targetPath, " ", "/")

			if sourceDir == "" {
				return targetPath
			}

			rel, err := filepath.Rel(sourceDir, targetPath)
			if err != nil {
				return targetPath
			}
			return filepath.ToSlash(rel)
		},
		"pathFor": func(d YamlDoc) string {
			// Construct path: /latest/cli/commands/parent/child
			// We need to strip "versori " prefix from Name and replace spaces with /
			path := strings.TrimPrefix(d.Name, "versori ")
			return strings.ReplaceAll(path, " ", "/")
		},
		"formatFlag": func(s string) string {
			if len(s) == 1 {
				return "-" + s
			}
			return "--" + s
		},
		"formatFlagLong": func(s string) string {
			return "--" + s
		},
		"lower": strings.ToLower,
		"join":  strings.Join,
		"trimPrefix": func(s string) string {
			return strings.TrimPrefix(s, "versori ")
		},
		"singleLine": func(s string) string {
			s = strings.ReplaceAll(s, "\n", " ")
			s = strings.ReplaceAll(s, "\r", "")
			return strings.TrimSpace(s)
		},
		"mdxSafe": mdxSafe,
	}).Parse(markdownTemplate)
	if err != nil {
		panic(err)
	}
}

// readYamlDocs reads all *.yaml files from dir and returns the parsed docs.
func readYamlDocs(dir string) ([]YamlDoc, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}

	docs := make([]YamlDoc, 0, len(entries))
	for _, path := range entries {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}

		var d YamlDoc
		if err := yaml.Unmarshal(data, &d); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}

		docs = append(docs, d)
	}

	return docs, nil
}

// populateDerivedFields fills NameSegments, Command, and Parent for every doc
// by splitting its Name on whitespace.
func populateDerivedFields(docs []YamlDoc) {
	for i := range docs {
		segs := strings.Fields(docs[i].Name)
		docs[i].NameSegments = segs
		if len(segs) > 0 {
			docs[i].Command = segs[len(segs)-1]
		}
		if len(segs) > 1 {
			docs[i].Parent = strings.Join(segs[:len(segs)-1], " ")
		}
	}
}

// buildTree assembles the flat slice of docs into a single tree rooted at the
// command that has no parent. Children are attached depth-first so that when a
// node is copied into its parent's SubCommands slice it already carries its own
// fully-populated SubCommands.
func buildTree(docs []YamlDoc) (YamlDoc, error) {
	// Index every doc by its Name for O(1) parent look-up.
	index := make(map[string]*YamlDoc, len(docs))
	for i := range docs {
		index[docs[i].Name] = &docs[i]
	}

	// Find the root (the only command with no parent).
	var root *YamlDoc
	for i := range docs {
		if docs[i].Parent == "" {
			root = &docs[i]
			break
		}
	}
	if root == nil {
		return YamlDoc{}, fmt.Errorf("no root command found")
	}

	// attach recursively populates d.SubCommands with all direct children,
	// each of which has already had its own children attached.
	var attach func(d *YamlDoc)
	attach = func(d *YamlDoc) {
		for i := range docs {
			if docs[i].Parent == d.Name {
				attach(&docs[i])                               // depth-first: grandchildren first
				d.SubCommands = append(d.SubCommands, docs[i]) // copy with SubCommands populated
			}
		}
	}
	attach(root)

	return *root, nil
}

func renderMarkdown(root *YamlDoc, outDir string) error {
	var generate func(d *YamlDoc) error

	generate = func(d *YamlDoc) error {
		// Only generate files for commands that have subcommands
		if len(d.SubCommands) > 0 {
			// Determine file path
			// versori -> outDir/index.md (optional, skipping root for now based on user request logic)
			// versori projects -> outDir/projects.md
			// versori projects asset -> outDir/projects/asset.md

			if d.Name == "versori" {
				// Skip root generation for now as user focused on subcommands
			} else {
				parts := d.NameSegments
				// Remove "versori"
				if len(parts) > 0 && parts[0] == "versori" {
					parts = parts[1:]
				}

				if len(parts) > 0 {
					// Last part is filename, previous parts are directory
					dir := filepath.Join(outDir, filepath.Join(parts[:len(parts)-1]...))
					if err := os.MkdirAll(dir, 0755); err != nil {
						return err
					}

					// Use command name for filename.
					filename := parts[len(parts)-1] + ".md"
					path := filepath.Join(dir, filename)

					f, err := os.Create(path)
					if err != nil {
						return err
					}
					defer func() { _ = f.Close() }()

					if err := mdTmpl.Execute(f, d); err != nil {
						return err
					}
				}
			}

			// Recurse
			for i := range d.SubCommands {
				if err := generate(&d.SubCommands[i]); err != nil {
					return err
				}
			}
		}
		return nil
	}

	return generate(root)
}

func main() {
	flag.Parse()

	// Ensure output directories exist
	err := os.MkdirAll("./docs_yaml", 0755)
	if err != nil {
		panic(err)
	}
	err = os.MkdirAll(outDir, 0755)
	if err != nil {
		panic(err)
	}

	rootCmd := cmd.GetRootCommand()

	// Disable the default "Auto generated by spf13/cobra" footer in YAML
	rootCmd.DisableAutoGenTag = true

	err = doc.GenYamlTree(rootCmd, "./docs_yaml")
	if err != nil {
		panic(err)
	}

	docs, err := readYamlDocs("./docs_yaml")
	if err != nil {
		panic(err)
	}

	populateDerivedFields(docs)

	tree, err := buildTree(docs)
	if err != nil {
		panic(err)
	}

	if err := renderMarkdown(&tree, outDir); err != nil {
		panic(err)
	}
}
